# Generated by Django 5.2 on 2025-04-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_emailtemplate_body_alter_emailtemplate_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
